--- |-
  <p><strong><a href="http://doodle.com/4azd55upq9b4zy2c" target="_blank">点我投票：PhotoShop培训时间</a></strong><br/>
  <strong><a href="http://doodle.com/iavxue65nx7wq7zt" target="_blank">点我投票：Python培训时间</a></strong></p>
  在宿舍无法上网的同学请用手机或在教学楼、图书馆等处投票。<br/>
