--- |-
  <h1><strong>网站<a href="//fuli.eesast.com">新域名</a>正式上线：<a href="//fuli.eesast.com">http://fuli.eesast.com</a></strong></h1>
  <p>根据投票结果，PS培训将于<strong>15日本周六下午14:30-16:30</strong>进行；</p><p>Python培训将于<strong>16日本周日下午14:30-16:30</strong>进行。上课地点均为<strong>罗姆楼10-208</strong></p>
